const config = {
  trailingComma: 'es5',
  tabWidth: 2,
  semi: true,
  singleQuote: true,
  jsxSingleQuote: false,
  endOfLine: 'lf',
  printWidth: 109,
  useTabs: false,
  bracketSpacing: true,
  jsxBracketSameLine: false,
  arrowParens: 'avoid',
  importOrder: [
    '^react(?:[/-].*)?$',
    '^.*react(?:-[^/]*)?$',
    '^[./]',
    '__tests__',
    '__mocks__',
    '^.*/api',
    '^.*/common',
    '^.*/data',
    '^.*/entries',
    '^.*/helpers',
    '^.*/hooks|^.*use-',
    '^.*/icons',
    '^.*/layers',
    '^.*/pages',
    '^.*/store/actions',
    '^.*/store/reducers',
    '^.*/tests',
    '^.*/types',
    '^.*/utils',
    '^../*',
    '<THIRD_PARTY_MODULES>',
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
  plugins: ['@trivago/prettier-plugin-sort-imports'],
};

export default config;
