const config = {
  trailingComma: 'es5',
  tabWidth: 2,
  semi: true,
  singleQuote: true,
  jsxSingleQuote: false,
  endOfLine: 'lf',
  printWidth: 109,
  useTabs: false,
  bracketSpacing: true,
  jsxBracketSameLine: false,
  arrowParens: 'avoid',
  importOrder: [
    '^react(?:[/-].*)?$',
    '^.*react(?:-[^/]*)?$',
    '<THIRD_PARTY_MODULES>',
    '^.*/api(?:/.*)?$',
    '^.*/common(?:/.*)?$',
    '^.*/data(?:/.*)?$',
    '^.*/entries(?:/.*)?$',
    '^.*/helpers(?:/.*)?$',
    '^.*/hooks-(?:/.*)?$',
    '^.*/icons(?:/.*)?$',
    '^.*/layers(?:/.*)?$',
    '^.*/pages(?:/.*)?$',
    '^.*/store/actions(?:/.*)?$',
    '^.*/store/reducers(?:/.*)?$',
    '^.*/test(?:/.*)?$',
    '^.*/types(?:/.*)?$',
    '^.*/utils(?:/.*)?$',
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
  plugins: ['@trivago/prettier-plugin-sort-imports'],
};

export default config;
