import { FC } from 'react'
import styles from './about.module.scss'
interface AboutProps {

}

const About: FC<AboutProps> = () => {
    return <div className={styles.mt}>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusantium aspernatur autem ducimus est exercitationem harum illo in incidunt, inventore ipsum itaque iure nemo nihil obcaecati optio praesentium quibusdam quo!</p>
    </div>;
}

export default About;